REPO_DIR=$(realpath $(realpath $(dirname $PWD)/dependencies))
HOSTNAME=$(cat /etc/hostname)
DOCKER_DIR=$REPO_DIR
IMAGE_NAME=${IMAGE_NAME:-project_python}
CONTAINER_USER=user
CONTAINER_HOME=/home/$CONTAINER_USER
CONTAINER_REPO_DIR=/repository
CONTAINER_PERSISTENT_DIR=/persistent
CONTAINER_PERSISTENT_VOLUME=project_python-persistent-data
CONTAINER_NAME=project_python