#!/usr/bin/env bash

source utils.sh

git clone --recursive https://github.com/mapillary/OpenSfM
cd OpenSfM
git submodule update --init --recursive

pip3 install -r requirements.txt && \
    python3 setup.py build \
    || exit_on_error
