#!/usr/bin/env bash

source utils.sh

git clone https://github.com/ArthurWuTW/OpenSfM.git
cd OpenSfM

pip3 install -r requirements.txt && \
    python3 setup.py build \
    || exit_on_error

pip3 install termcolor pause || exit_on_error
